### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [body20002/nova#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by 0x61nas** [comment]
You're right, I think a MIT license would be appropriate

**Comment by body20002** [comment]
@unixorn I've added a license file and a screenshots folder, check the repo readme file

**Comment by unixorn** [comment]
Thanks, adding it.
